config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

  resources :subscriptions, only: [], param: :confirm_token do
    member do
      get :confirm_email
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if pincode_required?
      redirect_to @event, alert: I18n.t('controllers.comments.error')
    elsif check_captcha(@new_comment) && @new_comment.save
      notify_subscribers(@event, @new_comment)
      redirect_to @event, notice: I18n.t('controllers.comments.created')
    else
      render 'events/show', alert: I18n.t('controllers.comments.error')
    end
  end

  def destroy
    message = { notice: I18n.t('controllers.comments.destroyed') }

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = { alert: I18n.t('controllers.comments.error') }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end

  def notify_subscribers(event, comment)
    all_emails = (event.subscriptions.confirmed.map(&:user_email) + [event.user.email]).uniq
    all_emails -= [current_user.email] if current_user

    all_emails.each do |email|
      EventMailer.comment(event, comment, email).deliver_now
    end
  end

  def pincode_required?
    @event.user != current_user &&
      @event.pincode.present? &&
      !@event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.buffer-bottom
  p = comment.body
  p
    span
      - if comment.user.present?
        = render partial: 'users/user', object: comment.user
      - else
        em
          strong = comment.user_name
    = ' '
    em = l comment.created_at, format: :short
    - if current_user_can_edit?(comment)
      = ' '
      = link_to gi_icon('trash'), event_comment_path(comment.event, comment),
              method: :delete, data: { confirm: 'Вы уверены, что хотите удалить комментарий?' }

app/views/comments/_form.html.slim
= form_for [@event, comment], html: {id: 'invisible-recaptcha-form'} do |f|
  = render partial: 'partials/form_errors', locals: { model: comment }

  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'

  - unless signed_in?
    .form-group
      = f.label :user_name
      = f.text_field :user_name, class: 'form-control'

  .actions
    -if signed_in?
      = f.submit 'Отправить', class: 'btn btn-primary'
    -else
      = invisible_recaptcha_tags callback: 'submitInvisibleRecaptchaForm', text: 'Отправить', class: 'btn btn-primary'