config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

  resources :subscriptions, only: [], param: :confirm_token do
    member do
      get :confirm_email
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: :destroy

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if pincode_required?
      redirect_to @event, alert: I18n.t('controllers.photos.error')
    elsif @new_photo.save
      notify_subscribers(@event, @new_photo)
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = { notice: I18n.t('controllers.photos.destroyed') }

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = { alert: I18n.t('controllers.photos.error') }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end

  def notify_subscribers(event, photo)
    all_emails = (event.subscriptions.confirmed.map(&:user_email) + [event.user.email]).uniq
    all_emails -= [current_user.email]

    all_emails.each do |email|
      EventMailer.photo(event, photo, email).deliver_now
    end
  end

  def pincode_required?
    @event.user != current_user &&
      @event.pincode.present? &&
      !@event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
  end
end

app/views/photos/_form.html.slim
= form_for [@event, photo], html: { multipart: true } do |f|
  = render partial: 'partials/form_errors', locals: { model: photo }

  .form-group
    = f.label :photo
    = f.file_field :photo

  .actions
    = f.submit 'Загрузить', class: 'btn btn-primary'

app/views/photos/_photo.html.slim
- if photo.user.present?
  - user = render partial: 'users/user', object: photo.user
- else
  - user = '<i>Удаленный пользователь</i>'

- title = "Добавил #{user}"

- if current_user_can_edit?(photo)
  - title += ' '
  - title += link_to gi_icon('trash'), event_photo_path(photo.event, photo),
          method: :delete, data: {confirm: 'Вы уверены, что хотите удалить фотку?'}

.event-photo.buffer-bottom
  = link_to image_tag(photo.photo.thumb.url, class: 'example-image'), photo.photo.url,
          data: { toggle: 'lightbox', gallery: "event-#{photo.event.id}", title: title }, class: 'example-image-link'